namespace WsiuRenderer {
[default_interface] runtimeclass EngineCore {
    EngineCore();
    void Initialize(Microsoft.UI.Xaml.Controls.SwapChainPanel panel);
    void Update();
    void Render();

    Boolean VSync;
}
} // namespace WsiuRenderer