import "KeyboardInputState.idl";
import "MouseInputState.idl";

namespace WsiuRenderer
{
    delegate void EditorWindowCallback();

    [default_interface] runtimeclass EngineCore
    {
        EngineCore();
        void Initialize(UInt64 windowHandle, Microsoft.UI.Xaml.Controls.SwapChainPanel panel);
        void BeginFrame();
        void Tick();
        void EndFrame();
        void Quit();

        UInt64 EditorWindowCreate(String title);
        void EditorWindowDestroy(UInt64 id);
        void EditorWindowChangeTitle(UInt64 id, String newTitle);
        void EditorWindowBeginCallback(UInt64 id, EditorWindowCallback handler);
        void EditorWindowDrawCallback(UInt64 id, EditorWindowCallback handler);
        void EditorWindowEndCallback(UInt64 id, EditorWindowCallback handler);

        Boolean VSync;

        UInt64 RtvBackBufferID { get; };
        MouseInputState InputMouseState { get; };
        KeyboardInputState InputKeyboardState { get; };
    }
} // namespace WsiuRenderer