namespace WsiuRenderer
{
    enum ImGuiSliderFlags
    {
        None               = 0,
        Logarithmic        = 1 << 5,       // Make the widget logarithmic (linear otherwise). Consider using ImGuiSliderFlags_NoRoundToFormat with this if using a format-string with small amount of digits.
        NoRoundToFormat    = 1 << 6,       // Disable rounding underlying value to match precision of the display format string (e.g. %.3f values are rounded to those 3 digits).
        NoInput            = 1 << 7,       // Disable Ctrl+Click or Enter key allowing to input text directly into the widget.
        WrapAround         = 1 << 8,       // Enable wrapping around from max to min and from min to max. Only supported by DragXXX() functions for now.
        ClampOnInput       = 1 << 9,       // Clamp value to min/max bounds when input manually with Ctrl+Click. By default Ctrl+Click allows going out of bounds.
        ClampZeroRange     = 1 << 10,      // Clamp even if min==max==0.0f. Otherwise due to legacy reason DragXXX functions don't clamp with those values. When your clamping limits are dynamic you almost always want to use it.
        NoSpeedTweaks      = 1 << 11,      // Disable keyboard modifiers altering tweak speed. Useful if you want to alter tweak speed yourself based on your own logic.
        ColorMarkers       = 1 << 12,      // DragScalarN(), SliderScalarN(): Draw R/G/B/A color markers on each component.
        AlwaysClamp        = ClampOnInput | ClampZeroRange,
    };

    enum ImGuiStyleVar
    {
        // Enum name -------------------------- // Member in ImGuiStyle structure (see ImGuiStyle for descriptions)
        Alpha,                       // float     Alpha
        DisabledAlpha,               // float     DisabledAlpha
        WindowPadding,               // ImVec2    WindowPadding
        WindowRounding,              // float     WindowRounding
        WindowBorderSize,            // float     WindowBorderSize
        WindowMinSize,               // ImVec2    WindowMinSize
        WindowTitleAlign,            // ImVec2    WindowTitleAlign
        ChildRounding,               // float     ChildRounding
        ChildBorderSize,             // float     ChildBorderSize
        PopupRounding,               // float     PopupRounding
        PopupBorderSize,             // float     PopupBorderSize
        FramePadding,                // ImVec2    FramePadding
        FrameRounding,               // float     FrameRounding
        FrameBorderSize,             // float     FrameBorderSize
        ItemSpacing,                 // ImVec2    ItemSpacing
        ItemInnerSpacing,            // ImVec2    ItemInnerSpacing
        IndentSpacing,               // float     IndentSpacing
        CellPadding,                 // ImVec2    CellPadding
        ScrollbarSize,               // float     ScrollbarSize
        ScrollbarRounding,           // float     ScrollbarRounding
        ScrollbarPadding,            // float     ScrollbarPadding
        GrabMinSize,                 // float     GrabMinSize
        GrabRounding,                // float     GrabRounding
        ImageRounding,               // float     ImageRounding
        ImageBorderSize,             // float     ImageBorderSize
        TabRounding,                 // float     TabRounding
        TabBorderSize,               // float     TabBorderSize
        TabMinWidthBase,             // float     TabMinWidthBase
        TabMinWidthShrink,           // float     TabMinWidthShrink
        TabBarBorderSize,            // float     TabBarBorderSize
        TabBarOverlineSize,          // float     TabBarOverlineSize
        TableAngledHeadersAngle,     // float     TableAngledHeadersAngle
        TableAngledHeadersTextAlign, // ImVec2  TableAngledHeadersTextAlign
        TreeLinesSize,               // float     TreeLinesSize
        TreeLinesRounding,           // float     TreeLinesRounding
        ButtonTextAlign,             // ImVec2    ButtonTextAlign
        SelectableTextAlign,         // ImVec2    SelectableTextAlign
        SeparatorSize,               // float     SeparatorSize
        SeparatorTextBorderSize,     // float     SeparatorTextBorderSize
        SeparatorTextAlign,          // ImVec2    SeparatorTextAlign
        SeparatorTextPadding,        // ImVec2    SeparatorTextPadding
        DockingSeparatorSize,        // float     DockingSeparatorSize
        COUNT
    };

    enum ImGuiTreeNodeFlags
    {
        None                 = 0,
        Selected             = 1 << 0,   // Draw as selected
        Framed               = 1 << 1,   // Draw frame with background (e.g. for CollapsingHeader)
        AllowOverlap         = 1 << 2,   // Hit testing to allow subsequent widgets to overlap this one
        NoTreePushOnOpen     = 1 << 3,   // Don't do a TreePush() when open (e.g. for CollapsingHeader) = no extra indent nor pushing on ID stack
        NoAutoOpenOnLog      = 1 << 4,   // Don't automatically and temporarily open node when Logging is active (by default logging will automatically open tree nodes)
        DefaultOpen          = 1 << 5,   // Default node to be open
        OpenOnDoubleClick    = 1 << 6,   // Open on double-click instead of simple click (default for multi-select unless any _OpenOnXXX behavior is set explicitly). Both behaviors may be combined.
        OpenOnArrow          = 1 << 7,   // Open when clicking on the arrow part (default for multi-select unless any _OpenOnXXX behavior is set explicitly). Both behaviors may be combined.
        Leaf                 = 1 << 8,   // No collapsing, no arrow (use as a convenience for leaf nodes). Note: will always open a tree/id scope and return true. If you never use that scope, add NoTreePushOnOpen.
        Bullet               = 1 << 9,   // Display a bullet instead of arrow. IMPORTANT: node can still be marked open/close if you don't set the _Leaf flag!
        FramePadding         = 1 << 10,  // Use FramePadding (even for an unframed text node) to vertically align text baseline to regular widget height. Equivalent to calling AlignTextToFramePadding() before the node.
        SpanAvailWidth       = 1 << 11,  // Extend hit box to the right-most edge, even if not framed. This is not the default in order to allow adding other items on the same line without using AllowOverlap mode.
        SpanFullWidth        = 1 << 12,  // Extend hit box to the left-most and right-most edges (cover the indent area).
        SpanLabelWidth       = 1 << 13,  // Narrow hit box + narrow hovering highlight, will only cover the label text.
        SpanAllColumns       = 1 << 14,  // Frame will span all columns of its container table (label will still fit in current column)
        LabelSpanAllColumns  = 1 << 15,  // Label will span all columns of its container table
        //NoScrollOnOpen     = 1 << 16,  // FIXME: TODO: Disable automatic scroll on TreePop() if node got just open and contents is not visible
        NavLeftJumpsToParent = 1 << 17,  // Nav: left arrow moves back to parent. This is processed in TreePop() when there's an unfulfilled Left nav request remaining.
        CollapsingHeader     = Framed | NoTreePushOnOpen | NoAutoOpenOnLog,
    
        // [EXPERIMENTAL] Draw lines connecting TreeNode hierarchy. Discuss in GitHub issue #2920.
        // Default value is pulled from style.TreeLinesFlags. May be overridden in TreeNode calls.
        DrawLinesNone        = 1 << 18,  // No lines drawn
        DrawLinesFull        = 1 << 19,  // Horizontal lines to child nodes. Vertical line drawn down to TreePop() position: cover full contents. Faster (for large trees).
        DrawLinesToNodes     = 1 << 20,  // Horizontal lines to child nodes. Vertical line drawn down to bottom-most child node. Slower (for large trees).
    
        NavLeftJumpsBackHere = NavLeftJumpsToParent,  // Renamed in 1.92.0
        SpanTextWidth        = SpanLabelWidth,        // Renamed in 1.90.7
        //AllowItemOverlap   = AllowOverlap,          // Renamed in 1.89.7
    };

    enum ImGuiSelectableFlags
    {
        None               = 0,
        NoAutoClosePopups  = 1 << 0,   // Clicking this doesn't close parent popup window (overrides ImGuiItemFlags_AutoClosePopups)
        SpanAllColumns     = 1 << 1,   // Frame will span all columns of its container table (text will still fit in current column)
        AllowDoubleClick   = 1 << 2,   // Generate press events on double clicks too
        Disabled           = 1 << 3,   // Cannot be selected, display grayed out text
        AllowOverlap       = 1 << 4,   // (WIP) Hit testing to allow subsequent widgets to overlap this one
        Highlight          = 1 << 5,   // Make the item be displayed as if it is hovered
        SelectOnNav        = 1 << 6,   // Auto-select when moved into, unless Ctrl is held. Automatic when in a BeginMultiSelect() block.
    
        DontClosePopups    = NoAutoClosePopups,   // Renamed in 1.91.0
        //AllowItemOverlap = AllowOverlap,        // Renamed in 1.89.7
    };

    enum ImGuiCol
    {
        Text,
        TextDisabled,
        WindowBg, // Background of normal windows
        ChildBg,  // Background of child windows
        PopupBg,  // Background of popups, menus, tooltips windows
        Border,
        BorderShadow,
        FrameBg, // Background of checkbox, radio button, plot, slider, text input
        FrameBgHovered,
        FrameBgActive,
        TitleBg,          // Title bar
        TitleBgActive,    // Title bar when focused
        TitleBgCollapsed, // Title bar when collapsed
        MenuBarBg,
        ScrollbarBg,
        ScrollbarGrab,
        ScrollbarGrabHovered,
        ScrollbarGrabActive,
        CheckMark, // Checkbox tick and RadioButton circle
        SliderGrab,
        SliderGrabActive,
        Button,
        ButtonHovered,
        ButtonActive,
        Header, // Header* colors are used for CollapsingHeader, TreeNode, Selectable, MenuItem
        HeaderHovered,
        HeaderActive,
        Separator,
        SeparatorHovered,
        SeparatorActive,
        ResizeGrip,                // Resize grip in lower-right and lower-left corners of windows.
        ResizeGripHovered,
        ResizeGripActive,
        InputTextCursor,           // InputText cursor/caret
        TabHovered,                // Tab background, when hovered
        Tab,                       // Tab background, when tab-bar is focused & tab is unselected
        TabSelected,               // Tab background, when tab-bar is focused & tab is selected
        TabSelectedOverline,       // Tab horizontal overline, when tab-bar is focused & tab is selected
        TabDimmed,                 // Tab background, when tab-bar is unfocused & tab is unselected
        TabDimmedSelected,         // Tab background, when tab-bar is unfocused & tab is selected
        TabDimmedSelectedOverline, //..horizontal overline, when tab-bar is unfocused & tab is selected
        DockingPreview,            // Preview overlay color when about to docking something
        DockingEmptyBg,            // Background color for empty node (e.g. CentralNode with no window docked into it)
        PlotLines,
        PlotLinesHovered,
        PlotHistogram,
        PlotHistogramHovered,
        TableHeaderBg,         // Table header background
        TableBorderStrong,     // Table outer and header borders (prefer using Alpha=1.0 here)
        TableBorderLight,      // Table inner borders (prefer using Alpha=1.0 here)
        TableRowBg,            // Table row background (even rows)
        TableRowBgAlt,         // Table row background (odd rows)
        TextLink,              // Hyperlink color
        TextSelectedBg,        // Selected text inside an InputText
        TreeLines,             // Tree node hierarchy outlines when using ImGuiTreeNodeFlags_DrawLines
        DragDropTarget,        // Rectangle border highlighting a drop target
        DragDropTargetBg,      // Rectangle background highlighting a drop target
        UnsavedMarker,         // Unsaved Document marker (in window title and tabs)
        NavCursor,             // Color of keyboard/gamepad navigation cursor/rectangle, when visible
        NavWindowingHighlight, // Highlight window when using Ctrl+Tab
        NavWindowingDimBg,     // Darken/colorize entire screen behind the Ctrl+Tab window list, when active
        ModalWindowDimBg,      // Darken/colorize entire screen behind a modal window, when one is active
        COUNT,

        TabActive          = TabSelected,       // [renamed in 1.90.9]
        TabUnfocused       = TabDimmed,         // [renamed in 1.90.9]
        TabUnfocusedActive = TabDimmedSelected, // [renamed in 1.90.9]
        NavHighlight       = NavCursor,         // [renamed in 1.91.4]
    };
}
