import "EngineCore.idl";
import "ImguiEnums.idl";

namespace WsiuRenderer
{
    delegate void ButtonCallback();

    delegate void FloatChangedCallback(Single x);
    delegate void FloatNChangedCallback(Single[] val);

    delegate void DoubleChangedCallback(Double x);
    delegate void DoubleNChangedCallback(Double[] val);

    delegate void UInt16ChangedCallback(UInt16 v);
    delegate void UInt16NChangedCallback(UInt16[] v);

    delegate void UInt32ChangedCallback(UInt32 v);
    delegate void UInt32NChangedCallback(UInt32[] v);

    delegate void UInt64ChangedCallback(UInt64 v);
    delegate void UInt64NChangedCallback(UInt64[] v);

    delegate void Int16ChangedCallback(Int16 v);
    delegate void Int16NChangedCallback(Int16[] v);

    delegate void Int32ChangedCallback(Int32 v);
    delegate void Int32NChangedCallback(Int32[] v);

    delegate void Int64ChangedCallback(Int64 v);
    delegate void Int64NChangedCallback(Int64[] v);

    [bindable]
    [default_interface] 
    runtimeclass ImguiContext 
    {
        ImguiContext(EngineCore engineCore);
        static String SaveIniSettingsToMemory();
        static void LoadIniSettingsFromMemory(String data);
        void InitializeCommands(String title);
        void InitializeWindow(String title);
        void InitializeWindowClosable(String title);
        UInt64 GetWindowID();
        Boolean GetActive();
        void SetActive(Boolean active);
        void SetTitle(String newTitle);
        void Separator();
        void SeparatorText(String text);
        void PushID(UInt32 id);
        void PopID();
        void BeginDisabled();
        void EndDisabled();
        void BeginMainMenuBar();
        void EndMainMenuBar();
        void BeginMenu(String label);
        void BeginMenu(String label, Boolean enabled);
        void MenuItem(String label, ButtonCallback handle);
        void MenuItem(String label, Boolean selected, ButtonCallback handle);
        void MenuItem(String label, Boolean selected, Boolean enabled, ButtonCallback handle);
        void EndMenu();
        void TreeNodeEx(String label, ImGuiTreeNodeFlags flags);
        void TreePop();
        void PushStyleVar(ImGuiStyleVar style, Single x);
        void PushStyleVar(ImGuiStyleVar style, Single x, Single y);
        void PopStyleVar();
        void PopStyleVar(Int32 count);
        void PushStyleColor(ImGuiCol col, Single r, Single g, Single b, Single a);
        void PopStyleColor(Int32 count);
        void PopStyleColor();
        void Text(String text);
        void Selectable(String label, Boolean selected, ImGuiSelectableFlags flags, ButtonCallback handle);
        void Selectable(String label, Boolean selected, ImGuiSelectableFlags flags, Single x, Single y, ButtonCallback handle);
        void Button(String label, ButtonCallback handle);
        void Button(String label, Single x, Single y, ButtonCallback handle);
        static void SettingFloat(Single speed, Single min, Single max, String format, ImGuiSliderFlags flags);
        void DragFloat(String label, Single val, FloatChangedCallback handle);
        void DragFloatN(String label, Single[] val, FloatNChangedCallback handle);
        static void SettingDouble(Single speed, Double min, Double max, String format, ImGuiSliderFlags flags);
        void DragDouble(String label, Double val, DoubleChangedCallback handle);
        void DragDoubleN(String label, Double[] val, DoubleNChangedCallback handle);
        static void SettingUInt16(Single speed, UInt16 min, UInt16 max, String format, ImGuiSliderFlags flags);
        void DragUInt16(String label, UInt16 val, UInt16ChangedCallback handle);
        void DragUInt16N(String label, UInt16[] val, UInt16NChangedCallback handle);
        static void SettingUInt32(Single speed, UInt32 min, UInt32 max, String format, ImGuiSliderFlags flags);
        void DragUInt32(String label, UInt32 val, UInt32ChangedCallback handle);
        void DragUInt32N(String label, UInt32[] val, UInt32NChangedCallback handle);
        static void SettingUInt64(Single speed, UInt64 min, UInt64 max, String format, ImGuiSliderFlags flags);
        void DragUInt64(String label, UInt64 val, UInt64ChangedCallback handle);
        void DragUInt64N(String label, UInt64[] val, UInt64NChangedCallback handle);
        static void SettingInt16(Single speed, Int16 min, Int16 max, String format, ImGuiSliderFlags flags);
        void DragInt16(String label, Int16 val, Int16ChangedCallback handle);
        void DragInt16N(String label, Int16[] val, Int16NChangedCallback handle);
        static void SettingInt32(Single speed, Int32 min, Int32 max, String format, ImGuiSliderFlags flags);
        void DragInt32(String label, Int32 val, Int32ChangedCallback handle);
        void DragInt32N(String label, Int32[] val, Int32NChangedCallback handle);
        static void SettingInt64(Single speed, Int64 min, Int64 max, String format, ImGuiSliderFlags flags);
        void DragInt64(String label, Int64 val, Int64ChangedCallback handle);
        void DragInt64N(String label, Int64[] val, Int64NChangedCallback handle);
    } 
}
