import "EngineCore.idl";
import "ImguiEnums.idl";

namespace WsiuRenderer
{
    delegate void FloatChangedCallback(Single x);
    delegate void FloatNChangedCallback(Single[] val);

    delegate void DoubleChangedCallback(Double x);
    delegate void DoubleNChangedCallback(Double[] val);

    [bindable]
    [default_interface] 
    runtimeclass ImguiContext 
    {
        ImguiContext(EngineCore engineCore);
        void InitializeWindow(String title);
        void InitializeWindowClosable(String title);
        UInt64 GetWindowID();
        void SetActive(Boolean active);
        void SetTitle(String newTitle);
        void PushID(UInt32 id);
        void PopID();
        void BeginDisabled();
        void EndDisabled();
        void PushStyleVar(ImGuiStyleVar style, Single x);
        void PushStyleVar(ImGuiStyleVar style, Single x, Single y);
        void PopStyleVar();
        void PopStyleVar(Int32 count);
        void Text(String text); 
        static void SettingFloat(Single speed, Single min, Single max, String format, ImGuiSliderFlags flags);
        void DragFloat(String label, Single val, FloatChangedCallback handle);
        void DragFloatN(String label, Single[] val, FloatNChangedCallback handle);
        static void SettingDouble(Single speed, Double min, Double max, String format, ImGuiSliderFlags flags);
        void DragDouble(String label, Double val, DoubleChangedCallback handle);
        void DragDoubleN(String label, Double[] val, DoubleNChangedCallback handle);
    } 
}
