namespace WsiuRenderer
{
    struct ImcVec2
    {
        Single x;
        Single y;
    };

    enum ImGuiSliderFlags
    {
        None               = 0,
        Logarithmic        = 1 << 5,       // Make the widget logarithmic (linear otherwise). Consider using ImGuiSliderFlags_NoRoundToFormat with this if using a format-string with small amount of digits.
        NoRoundToFormat    = 1 << 6,       // Disable rounding underlying value to match precision of the display format string (e.g. %.3f values are rounded to those 3 digits).
        NoInput            = 1 << 7,       // Disable Ctrl+Click or Enter key allowing to input text directly into the widget.
        WrapAround         = 1 << 8,       // Enable wrapping around from max to min and from min to max. Only supported by DragXXX() functions for now.
        ClampOnInput       = 1 << 9,       // Clamp value to min/max bounds when input manually with Ctrl+Click. By default Ctrl+Click allows going out of bounds.
        ClampZeroRange     = 1 << 10,      // Clamp even if min==max==0.0f. Otherwise due to legacy reason DragXXX functions don't clamp with those values. When your clamping limits are dynamic you almost always want to use it.
        NoSpeedTweaks      = 1 << 11,      // Disable keyboard modifiers altering tweak speed. Useful if you want to alter tweak speed yourself based on your own logic.
        ColorMarkers       = 1 << 12,      // DragScalarN(), SliderScalarN(): Draw R/G/B/A color markers on each component.
        AlwaysClamp        = ClampOnInput | ClampZeroRange,
    };

    enum ImGuiStyleVar
    {
        // Enum name -------------------------- // Member in ImGuiStyle structure (see ImGuiStyle for descriptions)
        Alpha,                       // float     Alpha
        DisabledAlpha,               // float     DisabledAlpha
        WindowPadding,               // ImVec2    WindowPadding
        WindowRounding,              // float     WindowRounding
        WindowBorderSize,            // float     WindowBorderSize
        WindowMinSize,               // ImVec2    WindowMinSize
        WindowTitleAlign,            // ImVec2    WindowTitleAlign
        ChildRounding,               // float     ChildRounding
        ChildBorderSize,             // float     ChildBorderSize
        PopupRounding,               // float     PopupRounding
        PopupBorderSize,             // float     PopupBorderSize
        FramePadding,                // ImVec2    FramePadding
        FrameRounding,               // float     FrameRounding
        FrameBorderSize,             // float     FrameBorderSize
        ItemSpacing,                 // ImVec2    ItemSpacing
        ItemInnerSpacing,            // ImVec2    ItemInnerSpacing
        IndentSpacing,               // float     IndentSpacing
        CellPadding,                 // ImVec2    CellPadding
        ScrollbarSize,               // float     ScrollbarSize
        ScrollbarRounding,           // float     ScrollbarRounding
        ScrollbarPadding,            // float     ScrollbarPadding
        GrabMinSize,                 // float     GrabMinSize
        GrabRounding,                // float     GrabRounding
        ImageRounding,               // float     ImageRounding
        ImageBorderSize,             // float     ImageBorderSize
        TabRounding,                 // float     TabRounding
        TabBorderSize,               // float     TabBorderSize
        TabMinWidthBase,             // float     TabMinWidthBase
        TabMinWidthShrink,           // float     TabMinWidthShrink
        TabBarBorderSize,            // float     TabBarBorderSize
        TabBarOverlineSize,          // float     TabBarOverlineSize
        TableAngledHeadersAngle,     // float     TableAngledHeadersAngle
        TableAngledHeadersTextAlign, // ImVec2  TableAngledHeadersTextAlign
        TreeLinesSize,               // float     TreeLinesSize
        TreeLinesRounding,           // float     TreeLinesRounding
        ButtonTextAlign,             // ImVec2    ButtonTextAlign
        SelectableTextAlign,         // ImVec2    SelectableTextAlign
        SeparatorSize,               // float     SeparatorSize
        SeparatorTextBorderSize,     // float     SeparatorTextBorderSize
        SeparatorTextAlign,          // ImVec2    SeparatorTextAlign
        SeparatorTextPadding,        // ImVec2    SeparatorTextPadding
        DockingSeparatorSize,        // float     DockingSeparatorSize
        COUNT
    };

    enum ImGuiTreeNodeFlags
    {
        None                 = 0,
        Selected             = 1 << 0,   // Draw as selected
        Framed               = 1 << 1,   // Draw frame with background (e.g. for CollapsingHeader)
        AllowOverlap         = 1 << 2,   // Hit testing to allow subsequent widgets to overlap this one
        NoTreePushOnOpen     = 1 << 3,   // Don't do a TreePush() when open (e.g. for CollapsingHeader) = no extra indent nor pushing on ID stack
        NoAutoOpenOnLog      = 1 << 4,   // Don't automatically and temporarily open node when Logging is active (by default logging will automatically open tree nodes)
        DefaultOpen          = 1 << 5,   // Default node to be open
        OpenOnDoubleClick    = 1 << 6,   // Open on double-click instead of simple click (default for multi-select unless any _OpenOnXXX behavior is set explicitly). Both behaviors may be combined.
        OpenOnArrow          = 1 << 7,   // Open when clicking on the arrow part (default for multi-select unless any _OpenOnXXX behavior is set explicitly). Both behaviors may be combined.
        Leaf                 = 1 << 8,   // No collapsing, no arrow (use as a convenience for leaf nodes). Note: will always open a tree/id scope and return true. If you never use that scope, add NoTreePushOnOpen.
        Bullet               = 1 << 9,   // Display a bullet instead of arrow. IMPORTANT: node can still be marked open/close if you don't set the _Leaf flag!
        FramePadding         = 1 << 10,  // Use FramePadding (even for an unframed text node) to vertically align text baseline to regular widget height. Equivalent to calling AlignTextToFramePadding() before the node.
        SpanAvailWidth       = 1 << 11,  // Extend hit box to the right-most edge, even if not framed. This is not the default in order to allow adding other items on the same line without using AllowOverlap mode.
        SpanFullWidth        = 1 << 12,  // Extend hit box to the left-most and right-most edges (cover the indent area).
        SpanLabelWidth       = 1 << 13,  // Narrow hit box + narrow hovering highlight, will only cover the label text.
        SpanAllColumns       = 1 << 14,  // Frame will span all columns of its container table (label will still fit in current column)
        LabelSpanAllColumns  = 1 << 15,  // Label will span all columns of its container table
        //NoScrollOnOpen     = 1 << 16,  // FIXME: TODO: Disable automatic scroll on TreePop() if node got just open and contents is not visible
        NavLeftJumpsToParent = 1 << 17,  // Nav: left arrow moves back to parent. This is processed in TreePop() when there's an unfulfilled Left nav request remaining.
        CollapsingHeader     = Framed | NoTreePushOnOpen | NoAutoOpenOnLog,
    
        // [EXPERIMENTAL] Draw lines connecting TreeNode hierarchy. Discuss in GitHub issue #2920.
        // Default value is pulled from style.TreeLinesFlags. May be overridden in TreeNode calls.
        DrawLinesNone        = 1 << 18,  // No lines drawn
        DrawLinesFull        = 1 << 19,  // Horizontal lines to child nodes. Vertical line drawn down to TreePop() position: cover full contents. Faster (for large trees).
        DrawLinesToNodes     = 1 << 20,  // Horizontal lines to child nodes. Vertical line drawn down to bottom-most child node. Slower (for large trees).
    
        NavLeftJumpsBackHere = NavLeftJumpsToParent,  // Renamed in 1.92.0
        SpanTextWidth        = SpanLabelWidth,        // Renamed in 1.90.7
        //AllowItemOverlap   = AllowOverlap,          // Renamed in 1.89.7
    };

    enum ImGuiSelectableFlags
    {
        None               = 0,
        NoAutoClosePopups  = 1 << 0,   // Clicking this doesn't close parent popup window (overrides ImGuiItemFlags_AutoClosePopups)
        SpanAllColumns     = 1 << 1,   // Frame will span all columns of its container table (text will still fit in current column)
        AllowDoubleClick   = 1 << 2,   // Generate press events on double clicks too
        Disabled           = 1 << 3,   // Cannot be selected, display grayed out text
        AllowOverlap       = 1 << 4,   // (WIP) Hit testing to allow subsequent widgets to overlap this one
        Highlight          = 1 << 5,   // Make the item be displayed as if it is hovered
        SelectOnNav        = 1 << 6,   // Auto-select when moved into, unless Ctrl is held. Automatic when in a BeginMultiSelect() block.
    
        DontClosePopups    = NoAutoClosePopups,   // Renamed in 1.91.0
        //AllowItemOverlap = AllowOverlap,        // Renamed in 1.89.7
    };

    enum ImGuiCol
    {
        Text,
        TextDisabled,
        WindowBg, // Background of normal windows
        ChildBg,  // Background of child windows
        PopupBg,  // Background of popups, menus, tooltips windows
        Border,
        BorderShadow,
        FrameBg, // Background of checkbox, radio button, plot, slider, text input
        FrameBgHovered,
        FrameBgActive,
        TitleBg,          // Title bar
        TitleBgActive,    // Title bar when focused
        TitleBgCollapsed, // Title bar when collapsed
        MenuBarBg,
        ScrollbarBg,
        ScrollbarGrab,
        ScrollbarGrabHovered,
        ScrollbarGrabActive,
        CheckMark, // Checkbox tick and RadioButton circle
        SliderGrab,
        SliderGrabActive,
        Button,
        ButtonHovered,
        ButtonActive,
        Header, // Header* colors are used for CollapsingHeader, TreeNode, Selectable, MenuItem
        HeaderHovered,
        HeaderActive,
        Separator,
        SeparatorHovered,
        SeparatorActive,
        ResizeGrip,                // Resize grip in lower-right and lower-left corners of windows.
        ResizeGripHovered,
        ResizeGripActive,
        InputTextCursor,           // InputText cursor/caret
        TabHovered,                // Tab background, when hovered
        Tab,                       // Tab background, when tab-bar is focused & tab is unselected
        TabSelected,               // Tab background, when tab-bar is focused & tab is selected
        TabSelectedOverline,       // Tab horizontal overline, when tab-bar is focused & tab is selected
        TabDimmed,                 // Tab background, when tab-bar is unfocused & tab is unselected
        TabDimmedSelected,         // Tab background, when tab-bar is unfocused & tab is selected
        TabDimmedSelectedOverline, //..horizontal overline, when tab-bar is unfocused & tab is selected
        DockingPreview,            // Preview overlay color when about to docking something
        DockingEmptyBg,            // Background color for empty node (e.g. CentralNode with no window docked into it)
        PlotLines,
        PlotLinesHovered,
        PlotHistogram,
        PlotHistogramHovered,
        TableHeaderBg,         // Table header background
        TableBorderStrong,     // Table outer and header borders (prefer using Alpha=1.0 here)
        TableBorderLight,      // Table inner borders (prefer using Alpha=1.0 here)
        TableRowBg,            // Table row background (even rows)
        TableRowBgAlt,         // Table row background (odd rows)
        TextLink,              // Hyperlink color
        TextSelectedBg,        // Selected text inside an InputText
        TreeLines,             // Tree node hierarchy outlines when using ImGuiTreeNodeFlags_DrawLines
        DragDropTarget,        // Rectangle border highlighting a drop target
        DragDropTargetBg,      // Rectangle background highlighting a drop target
        UnsavedMarker,         // Unsaved Document marker (in window title and tabs)
        NavCursor,             // Color of keyboard/gamepad navigation cursor/rectangle, when visible
        NavWindowingHighlight, // Highlight window when using Ctrl+Tab
        NavWindowingDimBg,     // Darken/colorize entire screen behind the Ctrl+Tab window list, when active
        ModalWindowDimBg,      // Darken/colorize entire screen behind a modal window, when one is active
        COUNT,

        TabActive          = TabSelected,       // [renamed in 1.90.9]
        TabUnfocused       = TabDimmed,         // [renamed in 1.90.9]
        TabUnfocusedActive = TabDimmedSelected, // [renamed in 1.90.9]
        NavHighlight       = NavCursor,         // [renamed in 1.91.4]
    };

    enum ImGuiInputTextFlags
    {
        // Basic filters (also see CallbackCharFilter)
        None                = 0,
        CharsDecimal        = 1 << 0,   // Allow 0123456789.+-*/
        CharsHexadecimal    = 1 << 1,   // Allow 0123456789ABCDEFabcdef
        CharsScientific     = 1 << 2,   // Allow 0123456789.+-*/eE (Scientific notation input)
        CharsUppercase      = 1 << 3,   // Turn a..z into A..Z
        CharsNoBlank        = 1 << 4,   // Filter out spaces, tabs
    
        // Inputs
        AllowTabInput       = 1 << 5,   // Pressing TAB input a '\t' character into the text field
        EnterReturnsTrue    = 1 << 6,   // Return 'true' when Enter is pressed (as opposed to every time the value was modified). Consider using IsItemDeactivatedAfterEdit() instead!
        EscapeClearsAll     = 1 << 7,   // Escape key clears content if not empty, and deactivate otherwise (contrast to default behavior of Escape to revert)
        CtrlEnterForNewLine = 1 << 8,   // In multi-line mode: validate with Enter, add new line with Ctrl+Enter (default is opposite: validate with Ctrl+Enter, add line with Enter). Note that Shift+Enter always enter a new line either way.
    
        // Other options
        ReadOnly            = 1 << 9,   // Read-only mode
        Password            = 1 << 10,  // Password mode, display all characters as '*', disable copy
        AlwaysOverwrite     = 1 << 11,  // Overwrite mode
        AutoSelectAll       = 1 << 12,  // Select entire text when first taking mouse focus
        ParseEmptyRefVal    = 1 << 13,  // InputFloat(), InputInt(), InputScalar() etc. only: parse empty string as zero value.
        DisplayEmptyRefVal  = 1 << 14,  // InputFloat(), InputInt(), InputScalar() etc. only: when value is zero, do not display it. Generally used with ParseEmptyRefVal.
        NoHorizontalScroll  = 1 << 15,  // Disable following the cursor horizontally
        NoUndoRedo          = 1 << 16,  // Disable undo/redo. Note that input text owns the text data while active, if you want to provide your own undo/redo stack you need e.g. to call ClearActiveID().
    
        // Elide display / Alignment
        ElideLeft           = 1 << 17,  // When text doesn't fit, elide left side to ensure right side stays visible. Useful for path/filenames. Single-line only!
    
        // Callback features
        CallbackCompletion  = 1 << 18,  // Callback on pressing TAB (for completion handling)
        CallbackHistory     = 1 << 19,  // Callback on pressing Up/Down arrows (for history handling)
        CallbackAlways      = 1 << 20,  // Callback on each iteration. User code may query cursor position, modify text buffer.
        CallbackCharFilter  = 1 << 21,  // Callback on character inputs to replace or discard them. Modify 'EventChar' to replace or discard, or return 1 in callback to discard.
        CallbackResize      = 1 << 22,  // Callback on buffer capacity changes request (beyond 'buf_size' parameter value), allowing the string to grow. Notify when the string wants to be resized (for string types which hold a cache of their Size). You will be provided a new BufSize in the callback and NEED to honor it. (see misc/cpp/imgui_stdlib.h for an example of using this)
        CallbackEdit        = 1 << 23,  // Callback on any edit. Note that InputText() already returns true on edit + you can always use IsItemEdited(). The callback is useful to manipulate the underlying buffer while focus is active.
    
        // Multi-line Word-Wrapping [BETA]
        // - Not well tested yet. Please report any incorrect cursor movement, selection behavior etc. bug to https://github.com/ocornut/imgui/issues/3237.
        // - Wrapping style is not ideal. Wrapping of long words/sections (e.g. words larger than total available width) may be particularly unpleasing.
        // - Wrapping width needs to always account for the possibility of a vertical scrollbar.
        // - It is much slower than regular text fields.
        //   Ballpark estimate of cost on my 2019 desktop PC: for a 100 KB text buffer: +~0.3 ms (Optimized) / +~1.0 ms (Debug build).
        //   The CPU cost is very roughly proportional to text length, so a 10 KB buffer should cost about ten times less.
        WordWrap            = 1 << 24,  // InputTextMultiline(): word-wrap lines that are too long.
    
        // Obsolete names
        //AlwaysInsertMode  = AlwaysOverwrite   // [renamed in 1.82] name was not matching behavior
    };

    enum ImGuiTableFlags
    {
        // Features
        None                       = 0,
        Resizable                  = 1 << 0,   // Enable resizing columns.
        Reorderable                = 1 << 1,   // Enable reordering columns in header row (need calling TableSetupColumn() + TableHeadersRow() to display headers)
        Hideable                   = 1 << 2,   // Enable hiding/disabling columns in context menu.
        Sortable                   = 1 << 3,   // Enable sorting. Call TableGetSortSpecs() to obtain sort specs. Also see SortMulti and SortTristate.
        NoSavedSettings            = 1 << 4,   // Disable persisting columns order, width, visibility and sort settings in the .ini file.
        ContextMenuInBody          = 1 << 5,   // Right-click on columns body/contents will display table context menu. By default it is available in TableHeadersRow().
        // Decorations
        RowBg                      = 1 << 6,   // Set each RowBg color with ImGuiCol_TableRowBg or ImGuiCol_TableRowBgAlt (equivalent of calling TableSetBgColor with ImGuiTableBgFlags_RowBg0 on each row manually)
        BordersInnerH              = 1 << 7,   // Draw horizontal borders between rows.
        BordersOuterH              = 1 << 8,   // Draw horizontal borders at the top and bottom.
        BordersInnerV              = 1 << 9,   // Draw vertical borders between columns.
        BordersOuterV              = 1 << 10,  // Draw vertical borders on the left and right sides.
        BordersH                   = BordersInnerH | BordersOuterH, // Draw horizontal borders.
        BordersV                   = BordersInnerV | BordersOuterV, // Draw vertical borders.
        BordersInner               = BordersInnerV | BordersInnerH, // Draw inner borders.
        BordersOuter               = BordersOuterV | BordersOuterH, // Draw outer borders.
        Borders                    = BordersInner | BordersOuter,   // Draw all borders.
        NoBordersInBody            = 1 << 11,  // [ALPHA] Disable vertical borders in columns Body (borders will always appear in Headers). -> May move to style
        NoBordersInBodyUntilResize = 1 << 12,  // [ALPHA] Disable vertical borders in columns Body until hovered for resize (borders will always appear in Headers). -> May move to style
        // Sizing Policy (read above for defaults)
        SizingFixedFit             = 1 << 13,  // Columns default to _WidthFixed or _WidthAuto (if resizable or not resizable), matching contents width.
        SizingFixedSame            = 2 << 13,  // Columns default to _WidthFixed or _WidthAuto (if resizable or not resizable), matching the maximum contents width of all columns. Implicitly enable NoKeepColumnsVisible.
        SizingStretchProp          = 3 << 13,  // Columns default to _WidthStretch with default weights proportional to each columns contents widths.
        SizingStretchSame          = 4 << 13,  // Columns default to _WidthStretch with default weights all equal, unless overridden by TableSetupColumn().
        // Sizing Extra Options
        NoHostExtendX              = 1 << 16,  // Make outer width auto-fit to columns, overriding outer_size.x value. Only available when ScrollX/ScrollY are disabled and Stretch columns are not used.
        NoHostExtendY              = 1 << 17,  // Make outer height stop exactly at outer_size.y (prevent auto-extending table past the limit). Only available when ScrollX/ScrollY are disabled. Data below the limit will be clipped and not visible.
        NoKeepColumnsVisible       = 1 << 18,  // Disable keeping column always minimally visible when ScrollX is off and table gets too small. Not recommended if columns are resizable.
        PreciseWidths              = 1 << 19,  // Disable distributing remainder width to stretched columns (width allocation on a 100-wide table with 3 columns: Without this flag: 33,33,34. With this flag: 33,33,33). With larger number of columns, resizing will appear to be less smooth.
        // Clipping
        NoClip                     = 1 << 20,  // Disable clipping rectangle for every individual columns (reduce draw command count, items will be able to overflow into other columns). Generally incompatible with TableSetupScrollFreeze().
        // Padding
        PadOuterX                  = 1 << 21,  // Default if BordersOuterV is on. Enable outermost padding. Generally desirable if you have headers.
        NoPadOuterX                = 1 << 22,  // Default if BordersOuterV is off. Disable outermost padding.
        NoPadInnerX                = 1 << 23,  // Disable inner padding between columns (double inner padding if BordersOuterV is on, single inner padding if BordersOuterV is off).
        // Scrolling
        ScrollX                    = 1 << 24,  // Enable horizontal scrolling. Require 'outer_size' parameter of BeginTable() to specify the container size. Changes default sizing policy. Because this creates a child window, ScrollY is currently generally recommended when using ScrollX.
        ScrollY                    = 1 << 25,  // Enable vertical scrolling. Require 'outer_size' parameter of BeginTable() to specify the container size.
        // Sorting
        SortMulti                  = 1 << 26,  // Hold shift when clicking headers to sort on multiple column. TableGetSortSpecs() may return specs where (SpecsCount > 1).
        SortTristate               = 1 << 27,  // Allow no sorting, disable default sorting. TableGetSortSpecs() may return specs where (SpecsCount == 0).
        // Miscellaneous
        HighlightHoveredColumn     = 1 << 28,  // Highlight column headers when hovered (may evolve into a fuller highlight)
    
        // [Internal] Combinations and masks
        SizingMask_                = SizingFixedFit | SizingFixedSame | SizingStretchProp | SizingStretchSame,
    };

    enum ImGuiTableColumnFlags
    {
        // Input configuration flags
        None                  = 0,
        Disabled              = 1 << 0,   // Overriding/master disable flag: hide column, won't show in context menu (unlike calling TableSetColumnEnabled() which manipulates the user accessible state)
        DefaultHide           = 1 << 1,   // Default as a hidden/disabled column.
        DefaultSort           = 1 << 2,   // Default as a sorting column.
        WidthStretch          = 1 << 3,   // Column will stretch. Preferable with horizontal scrolling disabled (default if table sizing policy is _SizingStretchSame or _SizingStretchProp).
        WidthFixed            = 1 << 4,   // Column will not stretch. Preferable with horizontal scrolling enabled (default if table sizing policy is _SizingFixedFit and table is resizable).
        NoResize              = 1 << 5,   // Disable manual resizing.
        NoReorder             = 1 << 6,   // Disable manual reordering this column, this will also prevent other columns from crossing over this column.
        NoHide                = 1 << 7,   // Disable ability to hide/disable this column.
        NoClip                = 1 << 8,   // Disable clipping for this column (all NoClip columns will render in a same draw command).
        NoSort                = 1 << 9,   // Disable ability to sort on this field (even if ImGuiTableFlags_Sortable is set on the table).
        NoSortAscending       = 1 << 10,  // Disable ability to sort in the ascending direction.
        NoSortDescending      = 1 << 11,  // Disable ability to sort in the descending direction.
        NoHeaderLabel         = 1 << 12,  // TableHeadersRow() will submit an empty label for this column. Convenient for some small columns. Name will still appear in context menu or in angled headers. You may append into this cell by calling TableSetColumnIndex() right after the TableHeadersRow() call.
        NoHeaderWidth         = 1 << 13,  // Disable header text width contribution to automatic column width.
        PreferSortAscending   = 1 << 14,  // Make the initial sort direction Ascending when first sorting on this column (default).
        PreferSortDescending  = 1 << 15,  // Make the initial sort direction Descending when first sorting on this column.
        IndentEnable          = 1 << 16,  // Use current Indent value when entering cell (default for column 0).
        IndentDisable         = 1 << 17,  // Ignore current Indent value when entering cell (default for columns > 0). Indentation changes _within_ the cell will still be honored.
        AngledHeader          = 1 << 18,  // TableHeadersRow() will submit an angled header row for this column. Note this will add an extra row.
    
        // Output status flags, read-only via TableGetColumnFlags()
        IsEnabled             = 1 << 24,  // Status: is enabled == not hidden by user/api (referred to as "Hide" in _DefaultHide and _NoHide) flags.
        IsVisible             = 1 << 25,  // Status: is visible == is enabled AND not clipped by scrolling.
        IsSorted              = 1 << 26,  // Status: is currently part of the sort specs
        IsHovered             = 1 << 27,  // Status: is hovered by mouse
    
        // [Internal] Combinations and masks
        WidthMask_            = WidthStretch | WidthFixed,
        IndentMask_           = IndentEnable | IndentDisable,
        StatusMask_           = IsEnabled | IsVisible | IsSorted | IsHovered,
        NoDirectResize_       = 1 << 30,  // [Internal] Disable user resizing this column directly (it may however we resized indirectly from its left edge)
    };
}
