// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_WsiuRenderer_Class()
{
    return winrt::detach_abi(winrt::make<winrt::WsiuRenderer::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::WsiuRenderer
{
    Class::Class() :
        Class(make<WsiuRenderer::implementation::Class>())
    {
    }
}
