// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#include "winrt/WsiuRenderer.h"
namespace winrt::WsiuRenderer::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES Class_base : implements<D, WsiuRenderer::Class, I...>
    {
        using base_type = Class_base;
        using class_type = WsiuRenderer::Class;
        using implements_type = typename Class_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"WsiuRenderer.Class";
        }
    };
}
namespace winrt::WsiuRenderer::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES ClassT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = WsiuRenderer::Class;

        hstring GetRuntimeClassName() const
        {
            return L"WsiuRenderer.Class";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_CLASS_XAML_G_H) || __has_include("Class.xaml.g.h")

#include "Class.xaml.g.h"

#else

namespace winrt::WsiuRenderer::implementation
{
    template <typename D, typename... I>
    using ClassT = Class_base<D, I...>;
}

#endif
