// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_WsiuRenderer_2_H
#define WINRT_WsiuRenderer_2_H
#include "winrt/impl/WsiuRenderer.1.h"
WINRT_EXPORT namespace winrt::WsiuRenderer
{
    struct WINRT_IMPL_EMPTY_BASES Class : winrt::WsiuRenderer::IClass
    {
        Class(std::nullptr_t) noexcept {}
        Class(void* ptr, take_ownership_from_abi_t) noexcept : winrt::WsiuRenderer::IClass(ptr, take_ownership_from_abi) {}
        Class();
    };
}
#endif
