// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_WsiuRenderer_0_H
#define WINRT_WsiuRenderer_0_H
WINRT_EXPORT namespace winrt::WsiuRenderer
{
    struct IClass;
    struct Class;
}
namespace winrt::impl
{
    template <> struct category<winrt::WsiuRenderer::IClass>{ using type = interface_category; };
    template <> struct category<winrt::WsiuRenderer::Class>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::WsiuRenderer::Class> = L"WsiuRenderer.Class";
    template <> inline constexpr auto& name_v<winrt::WsiuRenderer::IClass> = L"WsiuRenderer.IClass";
    template <> inline constexpr guid guid_v<winrt::WsiuRenderer::IClass>{ 0xAF8A30FD,0xC8F3,0x5A3B,{ 0x9B,0xE7,0x9E,0x6E,0x16,0xBE,0x74,0x16 } }; // AF8A30FD-C8F3-5A3B-9BE7-9E6E16BE7416
    template <> struct default_interface<winrt::WsiuRenderer::Class>{ using type = winrt::WsiuRenderer::IClass; };
    template <> struct abi<winrt::WsiuRenderer::IClass>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_WsiuRenderer_IClass
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::WsiuRenderer::IClass>
    {
        template <typename D> using type = consume_WsiuRenderer_IClass<D>;
    };
}
#endif
